
version: '3'
services:
  nodejs:
    image: node:latest
    tty: true
    volumes:
    - /Users/sources/C++/webrtc/NodeJs/webserver:/usr/local/src/app/
    ports:
    - 8887:8887
    - 8888:8888
    working_dir: /usr/local/src/app/https
    command: /bin/sh -c "npm install express serve-index socket.io log4js && /bin/sh"
